name: "Latex to PDF"

on:
  [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/HLD.tex
      - name : Move PDF to docs
        run: |
          mkdir docs
          mv HLD.pdf docs/
      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/HLD.pdf
          git commit -m "Add compiled PDF for ${GITHUB_SHA}"
          git push origin HEAD:${{ github.ref_name }}
