name: "Latex to PDF"

on:
  [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            docs/HLD.tex
            docs/refs.bib
      - name : Move PDF to docs
        run: |
          mv HLD.pdf docs/
      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff -s --exit-code docs/HLD.tex docs/refs.bib; then
            echo "No changes detected. Skipping commit."
          else
            echo "Changes detected. Committing..."
            git add docs/HLD.pdf
            git commit -m "Add compiled PDF for ${GITHUB_SHA}"
            git push origin HEAD:${{ github.ref_name }}
          fi
