name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      TEST_DIR: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $TEST_DIR/requirements.txt
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        PYTHONPATH=$(pwd) pytest $TEST_DIR --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=html || echo "TEST_FAILED=true" >> $GITHUB_ENV
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov

    - name: Fail job if tests failed
      if: env.TEST_FAILED == 'true'
      run: exit 1